export const G_POSTER_PRESETS = [
  // User Requested Specific Movie Posters
  { key: 'lupin iii: the first', poster: 'https://m.media-amazon.com/images/M/MV5BM2UwMjlmZWEtZjBiMi00ZmJmLTg1MDAtOWQ4NjFjMTY5MzhkXkEyXkFqcGc@._V1_.jpg' },
  { key: 'lupin iii - the first', poster: 'https://m.media-amazon.com/images/M/MV5BM2UwMjlmZWEtZjBiMi00ZmJmLTg1MDAtOWQ4NjFjMTY5MzhkXkEyXkFqcGc@._V1_.jpg' },
  { key: 'lupin the first', poster: 'https://m.media-amazon.com/images/M/MV5BM2UwMjlmZWEtZjBiMi00ZmJmLTg1MDAtOWQ4NjFjMTY5MzhkXkEyXkFqcGc@._V1_.jpg' },
  { key: 'lupin 3rd the first', poster: 'https://m.media-amazon.com/images/M/MV5BM2UwMjlmZWEtZjBiMi00ZmJmLTg1MDAtOWQ4NjFjMTY5MzhkXkEyXkFqcGc@._V1_.jpg' },
  { key: 'gigante de ferro', poster: 'https://play-lh.googleusercontent.com/dx_4A3IfPJaFk2OdpldURP3x3Eqwt0KWvXuBmCMSUXOf_QLGOBMR86IlKBRusVl2SfDp' },
  { key: 'o gigante de ferro', poster: 'https://play-lh.googleusercontent.com/dx_4A3IfPJaFk2OdpldURP3x3Eqwt0KWvXuBmCMSUXOf_QLGOBMR86IlKBRusVl2SfDp' },
  { key: 'iron giant', poster: 'https://play-lh.googleusercontent.com/dx_4A3IfPJaFk2OdpldURP3x3Eqwt0KWvXuBmCMSUXOf_QLGOBMR86IlKBRusVl2SfDp' },
  // Exact File Name Presets (Highest Priority)
  { key: 'lilo & stitch 4k.mkv', poster: 'https://m.media-amazon.com/images/S/pv-target-images/0ce5b704f290a64a76634b36d9fc699f1a7fe8a362ae1ffb53d656ae743f0dd6.jpg' },
  { key: 'lilo & stitch 2002.mkv', poster: 'https://m.media-amazon.com/images/S/pv-target-images/0ce5b704f290a64a76634b36d9fc699f1a7fe8a362ae1ffb53d656ae743f0dd6.jpg' },
  { key: 'o corcunda de notre dames 2 - 2002.mkv', poster: 'https://m.media-amazon.com/images/S/pv-target-images/b9d2d7de72c5d73a05a0cf21f000cfcbac1eefe1cf6d6a8fdfe8ad36a26be1c3.jpg' },
  // User Requested Specific Disney / Pixar / DreamWorks / Movie Posters
  { key: 'bob esponja: o filme', poster: 'https://static.wikia.nocookie.net/dublagem/images/5/55/20101535.jpg/revision/latest?cb=20240930170312&path-prefix=pt-br' },
  { key: 'bob esponja - o filme', poster: 'https://static.wikia.nocookie.net/dublagem/images/5/55/20101535.jpg/revision/latest?cb=20240930170312&path-prefix=pt-br' },
  { key: 'como mágica', poster: 'https://m.media-amazon.com/images/M/MV5BNWFlNWM2Y2YtY2VhOC00MWFiLWExNWYtYWViYzJhMDQyMTJiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg' },
  { key: 'como magica', poster: 'https://m.media-amazon.com/images/M/MV5BNWFlNWM2Y2YtY2VhOC00MWFiLWExNWYtYWViYzJhMDQyMTJiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg' },
  { key: 'flow', poster: 'https://ingresso-a.akamaihd.net/prd/img/movie/flow/76da2f6d-3176-42b1-8f9c-acbcc4dfbde7.webp' },
  { key: 'lilo & stitch 2002', poster: 'https://m.media-amazon.com/images/S/pv-target-images/0ce5b704f290a64a76634b36d9fc699f1a7fe8a362ae1ffb53d656ae743f0dd6.jpg' },
  { key: 'lilo & stitch (2002)', poster: 'https://m.media-amazon.com/images/S/pv-target-images/0ce5b704f290a64a76634b36d9fc699f1a7fe8a362ae1ffb53d656ae743f0dd6.jpg' },
  { key: 'lilo e stitch 2002', poster: 'https://m.media-amazon.com/images/S/pv-target-images/0ce5b704f290a64a76634b36d9fc699f1a7fe8a362ae1ffb53d656ae743f0dd6.jpg' },
  { key: 'lilo & stitch 4k', poster: 'https://m.media-amazon.com/images/S/pv-target-images/0ce5b704f290a64a76634b36d9fc699f1a7fe8a362ae1ffb53d656ae743f0dd6.jpg' },
  { key: 'lilo & stitch 2', poster: 'https://m.media-amazon.com/images/M/MV5BMTUzMTAwMjg2M15BMl5BanBnXkFtZTcwMzQyMjAzMQ@@._V1_SX300.jpg' },
  { key: 'lilo e stitch 2', poster: 'https://m.media-amazon.com/images/M/MV5BMTUzMTAwMjg2M15BMl5BanBnXkFtZTcwMzQyMjAzMQ@@._V1_SX300.jpg' },
  { key: 'lilo & stitch', poster: 'https://m.media-amazon.com/images/S/pv-target-images/0ce5b704f290a64a76634b36d9fc699f1a7fe8a362ae1ffb53d656ae743f0dd6.jpg' },
  { key: 'lilo e stitch', poster: 'https://m.media-amazon.com/images/S/pv-target-images/0ce5b704f290a64a76634b36d9fc699f1a7fe8a362ae1ffb53d656ae743f0dd6.jpg' },
  { key: 'corcunda de notre dames 2', poster: 'https://m.media-amazon.com/images/S/pv-target-images/b9d2d7de72c5d73a05a0cf21f000cfcbac1eefe1cf6d6a8fdfe8ad36a26be1c3.jpg' },
  { key: 'o corcunda de notre dames 2', poster: 'https://m.media-amazon.com/images/S/pv-target-images/b9d2d7de72c5d73a05a0cf21f000cfcbac1eefe1cf6d6a8fdfe8ad36a26be1c3.jpg' },
  { key: 'corcunda de notre dame 2', poster: 'https://m.media-amazon.com/images/S/pv-target-images/b9d2d7de72c5d73a05a0cf21f000cfcbac1eefe1cf6d6a8fdfe8ad36a26be1c3.jpg' },
  { key: 'shrek para sempre', poster: 'https://br.web.img2.acsta.net/medias/nmedia/18/87/90/45/19962744.jpg' },
  { key: 'shrek terceiro', poster: 'https://cinema-em-cena.nyc3.cdn.digitaloceanspaces.com/reviews/776/jtsu9H1mZ3ecRTXAB0WhrTUiut2.jpg' },
  { key: 'zootopia 2', poster: 'https://lumiere-a.akamaihd.net/v1/images/image003_90a26c13.jpeg?region=0,45,770,770' },
  { key: 'avatar aang: o último mestre do ar', poster: 'https://m.media-amazon.com/images/S/pv-target-images/e77df5c3877f93653db9b017389f3413bd41b4d131cddef736183e9cc6c731d5.jpg' },
  { key: 'avatar aang', poster: 'https://m.media-amazon.com/images/S/pv-target-images/e77df5c3877f93653db9b017389f3413bd41b4d131cddef736183e9cc6c731d5.jpg' },
  // Specific Anime Movies (Must come before generic series keys)
  { key: 'gaiden', poster: 'https://cdn.myanimelist.net/images/anime/1667/112943.jpg' },
  { key: 'o filme (2020)', poster: 'https://cdn.myanimelist.net/images/anime/1825/110716.jpg' },
  { key: 'violet evergarden: o filme', poster: 'https://cdn.myanimelist.net/images/anime/1825/110716.jpg' },
  { key: 'afloat', poster: 'https://cdn.myanimelist.net/images/anime/1448/140857.jpg' },
  { key: 'koe no katachi', poster: 'https://cdn.myanimelist.net/images/anime/1122/96435.jpg' },
  { key: 'a silent voice', poster: 'https://cdn.myanimelist.net/images/anime/1122/96435.jpg' },
  { key: 'lucário', poster: 'https://cdn.myanimelist.net/images/anime/6/79257.jpg' },
  { key: 'lucario', poster: 'https://cdn.myanimelist.net/images/anime/6/79257.jpg' },

  // Anime Series (Season 1 Default Posters)
  { key: 'frieren', poster: 'https://m.media-amazon.com/images/M/MV5BZTI4ZGMxN2UtODlkYS00MTBjLWE1YzctYzc3NDViMGI0ZmJmXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'death parade', poster: 'https://media.kitsu.app/anime/poster_images/9969/original.png' },
  { key: 'fog hill', poster: 'https://media.kitsu.app/anime/poster_images/41361/original.jpg' },
  { key: 'hibike', poster: 'https://m.media-amazon.com/images/M/MV5BYTk2NGZmZWItNjhmNS00ZjViLTk2NDQtZmY1YWYyNmY3MTYzXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'houseki no kuni', poster: 'https://media.kitsu.app/anime/13521/poster_image/740b51f22eb9f5cc6211d7ba63a5b58d.png' },
  { key: 'kill la kill', poster: 'https://media.kitsu.app/anime/poster_images/7712/original.jpg' },
  { key: 'kyoukai no kanata', poster: 'https://m.media-amazon.com/images/M/MV5BZDFmNzZjMzItNmQ0Yy00NjFlLWJjNGEtMDNmMWMyMGE1ODM3XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'lord of mysteries', poster: 'https://m.media-amazon.com/images/M/MV5BMWE1ZWYwZGUtZjRmOS00NzUzLTlkZmUtMTEwMjNhNTVmNDIwXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'fujiko mine', poster: 'https://m.media-amazon.com/images/M/MV5BYmY2ODI1YTYtZDQ4Zi00NDU0LWFkMzktOGEyMzJjYzU0OTc0XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'mine fujiko', poster: 'https://m.media-amazon.com/images/M/MV5BYmY2ODI1YTYtZDQ4Zi00NDU0LWFkMzktOGEyMzJjYzU0OTc0XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'monster', poster: 'https://m.media-amazon.com/images/M/MV5BYzU2MWQ5NGQtYmNlMC00ZjJkLWJmODItZDM5MDM3YmUyMWJkXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'apotecária', poster: 'https://m.media-amazon.com/images/M/MV5BNjAxMmFjZjgtYjM1ZS00NzdmLTliZDktZmIyMzU5YTBlNDBmXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'apotecaria', poster: 'https://m.media-amazon.com/images/M/MV5BNjAxMmFjZjgtYjM1ZS00NzdmLTliZDktZmIyMzU5YTBlNDBmXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'sora yori mo tooi basho', poster: 'https://m.media-amazon.com/images/M/MV5BNmQzYjI2NjgtMDY1Yy00OWViLWE3NjUtZmQxZTYwMzRhYzY1XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'a place further than the universe', poster: 'https://m.media-amazon.com/images/M/MV5BNmQzYjI2NjgtMDY1Yy00OWViLWE3NjUtZmQxZTYwMzRhYzY1XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'place further than the universe', poster: 'https://m.media-amazon.com/images/M/MV5BNmQzYjI2NjgtMDY1Yy00OWViLWE3NjUtZmQxZTYwMzRhYzY1XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'sora yori', poster: 'https://m.media-amazon.com/images/M/MV5BNmQzYjI2NjgtMDY1Yy00OWViLWE3NjUtZmQxZTYwMzRhYzY1XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'gurren lagann', poster: 'https://media.kitsu.app/anime/poster_images/1801/original.jpg' },
  { key: 'violet evergarden', poster: 'https://media.kitsu.app/anime/poster_images/12230/original.jpg' },

  // Anime Movies & Series
  { key: 'guerra dos deuses', poster: 'https://media.kitsu.app/anime/46332/poster_image/da46b90cb70db0378044729b9b0977a2.jpg' },
  { key: 'chihiro', poster: 'https://media.kitsu.app/anime/poster_images/176/original.jpg' },
  { key: 'harlock', poster: 'https://m.media-amazon.com/images/M/MV5BODJiNDQwZjYtYWNlZS00YzE4LTk1NTUtNWZjNzQyOGIzMTRhXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'children of the sea', poster: 'https://m.media-amazon.com/images/M/MV5BYTYwZWI1MWUtZmNkMC00YjFhLThlNzYtMzY3YThiNjlmODRmXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'deep sea', poster: 'https://m.media-amazon.com/images/M/MV5BOGZhZTg3OTMtOGRiZC00YzFhLTg0ZjYtY2RiMmY4MGUxZWJkXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'dragon quest', poster: 'https://media.kitsu.app/anime/poster_images/42248/original.jpg' },
  { key: 'gantz', poster: 'https://media.kitsu.app/anime/poster_images/11498/original.jpg' },
  { key: 'ghost in the shell', poster: 'https://m.media-amazon.com/images/M/MV5BNzljMjA3MTQtMjM1OS00OGJjLWJiYzctZDRiMTk1NWI5YzQ5XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'fantasma do futuro', poster: 'https://m.media-amazon.com/images/M/MV5BNzljMjA3MTQtMjM1OS00OGJjLWJiYzctZDRiMTk1NWI5YzQ5XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'koe no katachi', poster: 'https://cdn.myanimelist.net/images/anime/1122/96435.jpg' },
  { key: 'a silent voice', poster: 'https://cdn.myanimelist.net/images/anime/1122/96435.jpg' },
  { key: 'liz and the blue bird', poster: 'https://media.kitsu.app/anime/poster_images/13618/original.jpg' },
  { key: 'cagliostro', poster: 'https://m.media-amazon.com/images/M/MV5BYjQwZWNkMTYtYTU2Ny00YzgyLTljYTMtNjc0MjRkNWY5NDM4XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'lupin iii: the first', poster: 'https://m.media-amazon.com/images/M/MV5BM2UwMjlmZWEtZjBiMi00ZmJmLTg1MDAtOWQ4NjFjMTY5MzhkXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'lupin the first', poster: 'https://m.media-amazon.com/images/M/MV5BM2UwMjlmZWEtZjBiMi00ZmJmLTg1MDAtOWQ4NjFjMTY5MzhkXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'mirai', poster: 'https://m.media-amazon.com/images/M/MV5BMGMxNzNjY2EtMTUxNi00MTU0LTg3NDUtYmM1YWRhYmFlMGE2XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'nezha 2', poster: 'https://m.media-amazon.com/images/M/MV5BYjIyMDc3ZmQtZTQyYy00NDhhLTlmMWEtYzM3MDYwNjRmY2NkXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'renascer da alma', poster: 'https://m.media-amazon.com/images/M/MV5BYjIyMDc3ZmQtZTQyYy00NDhhLTlmMWEtYzM3MDYwNjRmY2NkXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'ne zha 2', poster: 'https://m.media-amazon.com/images/M/MV5BYjIyMDc3ZmQtZTQyYy00NDhhLTlmMWEtYzM3MDYwNjRmY2NkXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'ne zha', poster: 'https://m.media-amazon.com/images/M/MV5BYmRlODVlZDAtNzcxOC00N2U2LWE4MmQtZTYzZjg3Yjg1MzUxXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'nezha', poster: 'https://m.media-amazon.com/images/M/MV5BYmRlODVlZDAtNzcxOC00N2U2LWE4MmQtZTYzZjg3Yjg1MzUxXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'castelo animado', poster: 'https://m.media-amazon.com/images/M/MV5BMTY1OTg0MjE3MV5BMl5BanBnXkFtZTcwNTUxMTkyMQ@@._V1_SX300.jpg' },
  { key: 'vagalumes', poster: 'https://m.media-amazon.com/images/M/MV5BNTY5MmE2OGMtN2IxNC00MDY4LTkwMGEtZDUzOTYyNWE0ZTNjXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg' },
  { key: 'perfect blue', poster: 'https://m.media-amazon.com/images/M/MV5BMzAwNDIzMzEtZDZkNC00ZDQ4LTk3ZDMtZjVhMTU2YzgzZTZiXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'princesa mononoke', poster: 'https://m.media-amazon.com/images/M/MV5BNjAzODViNGEtMjBkYi00N2U5LWJjNjAtY2U0MGJhZTEwOTU0XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'princess mononoke', poster: 'https://m.media-amazon.com/images/M/MV5BNjAzODViNGEtMjBkYi00N2U5LWJjNjAtY2U0MGJhZTEwOTU0XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'mononoke', poster: 'https://m.media-amazon.com/images/M/MV5BNjAzODViNGEtMjBkYi00N2U5LWJjNjAtY2U0MGJhZTEwOTU0XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'death of superman', poster: 'https://m.media-amazon.com/images/M/MV5BNWZkMjYzNjctYTMyZi00MjdjLTg5MzMtYjdhM2M0MTI5ZWFkXkEyXkFqcGdeQXVyNTc4MjczMTM@._V1_SX300.jpg' },
  { key: 'reign of the supermen', poster: 'https://m.media-amazon.com/images/M/MV5BOTQzYWM2NDYtNTc3MC00MDUxLTgxOWEtMjNmMmY4ODFkZWVmXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'superman/batman: apocalypse', poster: 'https://m.media-amazon.com/images/M/MV5BMjk3ODhmNjgtZjllOC00ZWZjLTkwYzQtNzc1Y2ZhMjY2ODE0XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg' },
  { key: 'apocalypse', poster: 'https://m.media-amazon.com/images/M/MV5BMjk3ODhmNjgtZjllOC00ZWZjLTkwYzQtNzc1Y2ZhMjY2ODE0XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg' },
  { key: 'redline', poster: 'https://m.media-amazon.com/images/M/MV5BMzMxYWE5ZjMtMGJiMi00YmZjLTg2MGEtMWY1YjBkNWUxNzQ5XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'sayonara', poster: 'https://media.kitsu.app/anime/poster_images/13612/original.jpg' },
  { key: 'gaiden', poster: 'https://cdn.myanimelist.net/images/anime/1667/112943.jpg' },
  { key: 'o filme (2020)', poster: 'https://cdn.myanimelist.net/images/anime/1825/110716.jpg' },
  { key: 'violet evergarden: o filme', poster: 'https://cdn.myanimelist.net/images/anime/1825/110716.jpg' },
  { key: 'marnie', poster: 'https://media.kitsu.app/anime/poster_images/8159/original.jpg' },
  { key: 'serpente 2', poster: 'https://m.media-amazon.com/images/M/MV5BNWExYTk0YmMtZGMxZS00NzI5LTlhM2EtZmJlYjQ4NzQ1NzE2XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'green snake', poster: 'https://m.media-amazon.com/images/M/MV5BNWExYTk0YmMtZGMxZS00NzI5LTlhM2EtZmJlYjQ4NzQ1NzE2XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'white snake', poster: 'https://m.media-amazon.com/images/M/MV5BNzU0YjdjMTMtNjUzMC00NjhlLTkxMzctNDdkZGZkMmYyOTJlXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'serpente branca', poster: 'https://m.media-amazon.com/images/M/MV5BNzU0YjdjMTMtNjUzMC00NjhlLTkxMzctNDdkZGZkMmYyOTJlXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'afloat', poster: 'https://cdn.myanimelist.net/images/anime/1448/140857.jpg' },
  { key: 'wolf children', poster: 'https://media.kitsu.app/anime/poster_images/6711/original.jpg' },
  { key: 'crianças lobo', poster: 'https://media.kitsu.app/anime/poster_images/6711/original.jpg' },
  
  // Pokémon Movies
  { key: 'pokemon 2000', poster: 'https://media.kitsu.app/anime/poster_images/1001/original.jpg' },
  { key: 'darkrai', poster: 'https://media.kitsu.app/anime/poster_images/2597/original.jpg' },
  { key: 'viajantes do tempo', poster: 'https://media.kitsu.app/anime/poster_images/1003/original.jpg' },
  { key: 'pokémon 4', poster: 'https://media.kitsu.app/anime/poster_images/1003/original.jpg' },
  { key: 'latios e latias', poster: 'https://media.kitsu.app/anime/poster_images/1004/original.jpg' },
  { key: 'pokémon 5', poster: 'https://media.kitsu.app/anime/poster_images/1004/original.jpg' },
  { key: 'jirachi', poster: 'https://media.kitsu.app/anime/poster_images/1005/original.jpg' },
  { key: 'alma gêmea', poster: 'https://media.kitsu.app/anime/poster_images/1006/original.jpg' },
  { key: 'lucário', poster: 'https://cdn.myanimelist.net/images/anime/6/79257.jpg' },
  { key: 'lucario', poster: 'https://cdn.myanimelist.net/images/anime/6/79257.jpg' },
  { key: 'evolução', poster: 'https://media.kitsu.app/anime/41871/poster_image/3eadcf949282d8782ed3a60922f91760.png' },
  { key: 'hoopa', poster: 'https://m.media-amazon.com/images/M/MV5BOTc4MzA2OTg1OF5BMl5BanBnXkFtZTgwNzcyNDAwODE@._V1_SX300.jpg' },
  { key: 'hoppa', poster: 'https://m.media-amazon.com/images/M/MV5BOTc4MzA2OTg1OF5BMl5BanBnXkFtZTgwNzcyNDAwODE@._V1_SX300.jpg' },
  { key: 'victini', poster: 'https://media.kitsu.app/anime/poster_images/5939/original.jpg' },
  { key: 'the first movie', poster: 'https://media.kitsu.app/anime/poster_images/1534/original.jpg' },
  { key: 'mewtwo contra-ataca', poster: 'https://media.kitsu.app/anime/poster_images/1534/original.jpg' },

  // Disney / Pixar / DreamWorks
  { key: 'casa monstro', poster: 'https://m.media-amazon.com/images/M/MV5BMTIzNjE1NDg1N15BMl5BanBnXkFtZTcwOTg2NTMzMQ@@._V1_SX300.jpg' },
  { key: 'era do gelo 2', poster: 'https://m.media-amazon.com/images/M/MV5BMjAwODg3OTAxMl5BMl5BanBnXkFtZTcwMjg2NjYyMw@@._V1_SX300.jpg' },
  { key: 'era do gelo 3', poster: 'https://m.media-amazon.com/images/M/MV5BZWJjZDYwMjgtZDZiMy00YzcyLThjN2YtYjI1ZDQ2ZDJkOTVmXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'era do gelo', poster: 'https://m.media-amazon.com/images/M/MV5BMDBlYzU2OGMtOGJjNi00ZGZjLWIwNjMtYzdiZjkwYWNjZDljXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'fera do mar', poster: 'https://m.media-amazon.com/images/M/MV5BZDhjZmY1ZDEtNGQ1ZC00ZDgwLWI2YjEtMWFiOGY3M2Q2YWViXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'onda do imperador', poster: 'https://m.media-amazon.com/images/M/MV5BMjM2MWU5ZDEtNDZlZC00ZmQ2LThiOTEtMmZkMzAxMmI5MGIyXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'princesa e o sapo', poster: 'https://m.media-amazon.com/images/M/MV5BOTE3YTExYTEtOTUxZC00OTM0LWJmYmItMDk5YjczNmIwNzA2XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'throne of atlantis', poster: 'https://m.media-amazon.com/images/M/MV5BMGYwYTBjYTEtODE1NS00OTA2LTk5ZTctM2I0ZWViMTc4NDljXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_SX300.jpg' },
  { key: 'trono de atlantis', poster: 'https://m.media-amazon.com/images/M/MV5BMGYwYTBjYTEtODE1NS00OTA2LTk5ZTctM2I0ZWViMTc4NDljXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_SX300.jpg' },
  { key: 'justice league: throne of atlantis', poster: 'https://m.media-amazon.com/images/M/MV5BMGYwYTBjYTEtODE1NS00OTA2LTk5ZTctM2I0ZWViMTc4NDljXkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_SX300.jpg' },
  { key: 'atlantis', poster: 'https://m.media-amazon.com/images/M/MV5BODYwZTQwMDEtYjgyZS00NzNhLWFhYWMtN2Q1Y2JmZjlmZDlhXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'bob esponja', poster: 'https://m.media-amazon.com/images/M/MV5BZTRhZDUzMjktOTJhMC00YjNlLTk5YjAtNTdiYTVmMzc1YT1kEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'carros 1', poster: 'https://m.media-amazon.com/images/M/MV5BMTg5NzY0MzA2MV5BMl5BanBnXkFtZTYwNDc3NTc2._V1_SX300.jpg' },
  { key: 'carros 3', poster: 'https://m.media-amazon.com/images/M/MV5BMTc0NzU2OTYyN15BMl5BanBnXkFtZTgwMTkwOTg2MTI@._V1_SX300.jpg' },
  { key: 'carros', poster: 'https://m.media-amazon.com/images/M/MV5BMTg5NzY0MzA2MV5BMl5BanBnXkFtZTYwNDc3NTc2._V1_SX300.jpg' },
  { key: 'coraline', poster: 'https://m.media-amazon.com/images/M/MV5BMzQxNjM5NzkxNV5BMl5BanBnXkFtZTcwMzg5NDMwMg@@._V1_SX300.jpg' },
  { key: 'divertida mente 2', poster: 'https://m.media-amazon.com/images/M/MV5BYWY3MDE2Y2UtOTE3Zi00MGUzLTg2MTItZjE1ZWVkMGVlODRmXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'divertida mente', poster: 'https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg' },
  { key: 'elementos', poster: 'https://m.media-amazon.com/images/M/MV5BNjU2MjE1OGItZjdmYS00ZmIyLTljNjYtOWI5ZGRkZjM4NDEwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg' },
  { key: 'encanto', poster: 'https://m.media-amazon.com/images/M/MV5BNGEyNzk2M2MtNjBhZS00MzYwLWI0Y2YtYjc5ZWE2MjM0YWE5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg' },
  { key: 'enrolados', poster: 'https://m.media-amazon.com/images/M/MV5BMTAxNDYxMjg0MjNeQTJeQWpwZ15BbWU3MDcyNTk2OTM@._V1_SX300.jpg' },
  { key: 'frozen', poster: 'https://m.media-amazon.com/images/M/MV5BMTQ1MjQwMTE5OF5BMl5BanBnXkFtZTgwNjk3MTcyMDE@._V1_SX300.jpg' },
  { key: 'gato de botas 2', poster: 'https://m.media-amazon.com/images/M/MV5BMzg0MWUzMjctYjVlOS00NzVjLWIwZDMtNzg1YzNkYzdjNTMwXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'gato de botas', poster: 'https://m.media-amazon.com/images/M/MV5BOTQwMGU5YTEtYmQzMy00MTM0LWFhNzAtOGY2Yzc1MzBkYTYyXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'happy feet 2', poster: 'https://m.media-amazon.com/images/M/MV5BMTI3ZTlkMmMtYWVmZS00M2QyLTkwNWYtNTdlYmIzNzI0NmFhXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'happy feet', poster: 'https://m.media-amazon.com/images/M/MV5BNjViZDZhNjctM2MwOS00MDdhLWIwMTYtNjNmNGY2OGMzZWZhXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'hotel transilvânia', poster: 'https://m.media-amazon.com/images/M/MV5BMTM3NjQyODI3M15BMl5BanBnXkFtZTcwMDM4NjM0OA@@._V1_SX300.jpg' },
  { key: 'hÉrcules', poster: 'https://m.media-amazon.com/images/M/MV5BMmUyZGY1ZjItMWYwZS00MjJjLTg1YzAtY2Q5OTA4MmFhYzFjXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'hércules', poster: 'https://m.media-amazon.com/images/M/MV5BMmUyZGY1ZjItMWYwZS00MjJjLTg1YzAtY2Q5OTA4MmFhYzFjXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'hercules', poster: 'https://m.media-amazon.com/images/M/MV5BMmUyZGY1ZjItMWYwZS00MjJjLTg1YzAtY2Q5OTA4MmFhYzFjXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'klaus', poster: 'https://m.media-amazon.com/images/M/MV5BZDA4ODhlMzctNGRmYi00NmViLTkxZGYtZjRkNGQ5YzYwYWVlXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'kung fu panda 2', poster: 'https://m.media-amazon.com/images/M/MV5BYmIxMGYzMTUtZDQzYy00ODc4LWE1YzQtZGMwYTc0YTYyYTE0XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'kung fu panda 3', poster: 'https://m.media-amazon.com/images/M/MV5BMTUyNzgxNjg2M15BMl5BanBnXkFtZTgwMTY1NDI1NjE@._V1_SX300.jpg' },
  { key: 'kung fu panda', poster: 'https://m.media-amazon.com/images/M/MV5BZDU5MDNiMGItYjVmZi00NDUxLTg2OTktNGE0NzNlNzM4NzgyXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'gahoole', poster: 'https://m.media-amazon.com/images/M/MV5BMjE0NjA5OTA4N15BMl5BanBnXkFtZTcwODA3MTA3Mw@@._V1_SX300.jpg' },
  { key: 'guardiões', poster: 'https://m.media-amazon.com/images/M/MV5BMjE0NjA5OTA4N15BMl5BanBnXkFtZTcwODA3MTA3Mw@@._V1_SX300.jpg' },
  { key: 'lilo & stitch 2', poster: 'https://m.media-amazon.com/images/M/MV5BMTUzMTAwMjg2M15BMl5BanBnXkFtZTcwMzQyMjAzMQ@@._V1_SX300.jpg' },
  { key: 'lilo & stitch', poster: 'https://m.media-amazon.com/images/M/MV5BYzRiYTA1YTEtMjYwMi00NGVhLThkOGYtZDBlYjNjZDk2NDEwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg' },
  { key: 'luca', poster: 'https://m.media-amazon.com/images/M/MV5BMWMyNGNlZTktODVkNS00ZmMyLTk0NmUtNWVjOWU1MWMzZGMzXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg' },
  { key: 'super mario', poster: 'https://m.media-amazon.com/images/M/MV5BOGZlN2EzOTYtMzUzOS00NTM3LTg0MTQtZDVjZGM4YmJlNWNhXkEyXkFqcGc@._V1_QL75_UY562_CR0,0,380,562_.jpg' },
  { key: 'meu malvado favorito', poster: 'https://m.media-amazon.com/images/M/MV5BMTY3NjY0MTQ0Nl5BMl5BanBnXkFtZTcwMzQ2MTc0Mw@@._V1_SX300.jpg' },
  { key: 'monstros s.a', poster: 'https://m.media-amazon.com/images/M/MV5BMTY1NTI0ODUyOF5BMl5BanBnXkFtZTgwNTEyNjQ0MDE@._V1_QL75_UX380_CR0,0,380,562_.jpg' },
  { key: 'universidade monstros', poster: 'https://m.media-amazon.com/images/M/MV5BMTUyODgwMDU3M15BMl5BanBnXkFtZTcwOTM4MjcxOQ@@._V1_SX300.jpg' },
  { key: 'mulan', poster: 'https://m.media-amazon.com/images/M/MV5BYzU0ZTQxZDktOGY0Yy00NjdiLTllNDItMTMzMjI1YjMyYjRhXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'caldeirão mágico', poster: 'https://m.media-amazon.com/images/M/MV5BYjEzNjJkNzktYmNmMy00ZmUzLWE3OTMtZTM2ZDU3ODNjOGMyXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'caminho para el dorado', poster: 'https://m.media-amazon.com/images/M/MV5BMjIyNDBmYTEtYjM3MS00NDhkLWFhNjYtZGYxYzA2OGUyZjQ2XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'corcunda de notre dame', poster: 'https://m.media-amazon.com/images/M/MV5BY2QzMGEzNGMtMDQyNC00YTlmLWEwYjMtOGI1NWYxMTM4NjA2XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'gigante de ferro', poster: 'https://m.media-amazon.com/images/M/MV5BODM4ZjZjMGEtYmFiMy00ThjLWIzZjUtMDU0ODg1NTI2MzIwXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'operação big hero', poster: 'https://m.media-amazon.com/images/M/MV5BYjQ3YzUyOGQtNjdlYS00YmRhLWIyOWYtMGQ3YjkwMjJiYzRjXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'os incríveis 2', poster: 'https://m.media-amazon.com/images/M/MV5BMTEzNzY0OTg0NTdeQTJeQWpwZ15BbWU4MDU3OTg3MjUz._V1_SX300.jpg' },
  { key: 'os incríveis', poster: 'https://m.media-amazon.com/images/M/MV5BMTY5OTU0OTc2NV5BMl5BanBnXkFtZTcwMzU4MDcyMQ@@._V1_SX300.jpg' },
  { key: 'pinóquio', poster: 'https://m.media-amazon.com/images/M/MV5BZGU3MTE3NjYtMGU1Zi00NjBmLTg4MzItZjg0OGZmNjZiYjQwXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'procurando nemo', poster: 'https://m.media-amazon.com/images/M/MV5BMTc5NjExNTA5OV5BMl5BanBnXkFtZTYwMTQ0ODY2._V1_SX300.jpg' },
  { key: 'rango', poster: 'https://m.media-amazon.com/images/M/MV5BMTc4NjEyODE1OV5BMl5BanBnXkFtZTcwMjYzNTkxNA@@._V1_SX300.jpg' },
  { key: 'ratatouille', poster: 'https://m.media-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_QL75_UX380_CR0,0,380,562_.jpg' },
  { key: 'raya', poster: 'https://m.media-amazon.com/images/M/MV5BN2QzZTQ3MzktN2JiYS00MDEzLTgxMWQtZWFmMDI3NWFkZTY0XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'rio', poster: 'https://m.media-amazon.com/images/M/MV5BMTU2MDY3MzAzMl5BMl5BanBnXkFtZTcwMTg0NjM5NA@@._V1_SX300.jpg' },
  { key: 'shrek 2', poster: 'https://m.media-amazon.com/images/M/MV5BMzNmNjQ1NmUtNzhiZS00YWE2LTg4N2ItZTA2ODdmOTMwOTQ1XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'shrek 3', poster: 'https://m.media-amazon.com/images/M/MV5BOTgyMjc3ODk2MV5BMl5BanBnXkFtZTcwMjY0MjEzMw@@._V1_SX300.jpg' },
  { key: 'shrek pra sempre', poster: 'https://m.media-amazon.com/images/M/MV5BMTY0OTU1NzkxMl5BMl5BanBnXkFtZTcwMzI2NDUzMw@@._V1_SX300.jpg' },
  { key: 'flow', poster: 'https://m.media-amazon.com/images/M/MV5BYzA2Nzk5M2EtOWJkYS00YWVmLTg4ODEtNWFlNGVjZDM3ZmI3XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'como mágica', poster: 'https://m.media-amazon.com/images/M/MV5BNDcwOTk2MmItZWM0Yi00ZDg2LTlhNDctOWM5MTdhM2UwZmFjXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'como magica', poster: 'https://m.media-amazon.com/images/M/MV5BNDcwOTk2MmItZWM0Yi00ZDg2LTlhNDctOWM5MTdhM2UwZmFjXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'shrek', poster: 'https://m.media-amazon.com/images/M/MV5BN2FkMTRkNTUtYTI0NC00ZjI4LWI5MzUtMDFmOGY0NmU2OGY1XkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'tintim', poster: 'https://m.media-amazon.com/images/M/MV5BNDE5MDExNTQ1OF5BMl5BanBnXkFtZTcwMDIxMTM5Ng@@._V1_SX300.jpg' },
  { key: 'tintin', poster: 'https://m.media-amazon.com/images/M/MV5BNDE5MDExNTQ1OF5BMl5BanBnXkFtZTcwMDIxMTM5Ng@@._V1_SX300.jpg' },
  { key: 'tico e teco', poster: 'https://m.media-amazon.com/images/M/MV5BMjIzY2Q1ZWYtOGQ0Yi00NTllLTkzYzgtMWZlZmY2NGViYzNhXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'toy story 1', poster: 'https://m.media-amazon.com/images/M/MV5BZTA3OWVjOWItNjE1NS00NzZiLWE1MjgtZDZhMWI1ZTlkNzYwXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'toy story 2', poster: 'https://m.media-amazon.com/images/M/MV5BNzVmODlhMDEtY2YxZi00OTVjLTlkNTktN2Q2OTRlM2I4M2FhXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'toy story 3', poster: 'https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg' },
  { key: 'toy story 4', poster: 'https://m.media-amazon.com/images/M/MV5BMTYzMDM4NzkxOV5BMl5BanBnXkFtZTgwNzM1Mzg2NzM@._V1_SX300.jpg' },
  { key: 'toy story', poster: 'https://m.media-amazon.com/images/M/MV5BZTA3OWVjOWItNjE1NS00NzZiLWE1MjgtZDZhMWI1ZTlkNzYwXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'up altas aventuras', poster: 'https://m.media-amazon.com/images/M/MV5BNmI1ZTc5MWMtMDYyOS00ZDc2LTkzOTAtNjQ4NWIxNjYyNDgzXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'up', poster: 'https://m.media-amazon.com/images/M/MV5BNmI1ZTc5MWMtMDYyOS00ZDc2LTkzOTAtNjQ4NWIxNjYyNDgzXkEyXkFqcGc@._V1_SX300.jpg' },
  { key: 'valente', poster: 'https://m.media-amazon.com/images/M/MV5BMzgwODk3ODA1NF5BMl5BanBnXkFtZTcwNjU3NjQ0Nw@@._V1_SX300.jpg' },
  { key: 'wifi ralph', poster: 'https://m.media-amazon.com/images/M/MV5BMTYyNzEyNDAzOV5BMl5BanBnXkFtZTgwNTk3NDczNjM@._V1_SX300.jpg' },
  { key: 'zootopia', poster: 'https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_QL75_UX380_CR0,0,380,562_.jpg' }
];

export function getGDrivePoster(titleOrKey) {
  const str = String(titleOrKey).toLowerCase();
  const match = G_POSTER_PRESETS.find(p => str.includes(p.key));
  return match ? match.poster : null;
}
